import type { ImportedFormat } from '../types'

/**
 * Where `cartridge-artifact.browser.test.ts` writes the real cartridges it
 * builds, and where `cartridge-artifact.test.ts` reads them back from to run
 * a real `unzip` against them.
 *
 * A shared module, not a literal path typed out twice, so the writer and the
 * reader cannot silently disagree on the filename and end up talking past
 * each other — the browser file would keep "passing" while writing to a path
 * the node file never looks at, and the node file would keep "passing" by
 * finding nothing wrong with a file it never opened.
 *
 * Lives under `artifacts/`, which `.gitignore` already excludes — the same
 * directory `packaged-cartridge.browser.test.ts` writes its own tracer
 * cartridge into. Generated bytes never belong in the repository.
 */
export const CARTRIDGE_ARTIFACT_DIR = 'artifacts/cartridge-artifact'

export function cartridgeArtifactPath(format: ImportedFormat): string {
  return `${CARTRIDGE_ARTIFACT_DIR}/${format}.imscc`
}
